/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a predefined field of the issue. Predefined fields are always present in an issue and             |cannot be customized in a project. For example, `project`, `created`,             |`updated`, `tags`, and so on.
type PredefinedFilterField struct {
	Name  string `json:"name,omitempty"`
	Id    string `json:"id,omitempty"`
	Type_ string `json:"$type,omitempty"`
}
