/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the settings of a link type in YouTrack.
type IssueLinkType struct {
	Name                    string `json:"name,omitempty"`
	LocalizedName           string `json:"localizedName,omitempty"`
	SourceToTarget          string `json:"sourceToTarget,omitempty"`
	LocalizedSourceToTarget string `json:"localizedSourceToTarget,omitempty"`
	TargetToSource          string `json:"targetToSource,omitempty"`
	LocalizedTargetToSource string `json:"localizedTargetToSource,omitempty"`
	Directed                bool   `json:"directed,omitempty"`
	Aggregation             bool   `json:"aggregation,omitempty"`
	ReadOnly                bool   `json:"readOnly,omitempty"`
	Id                      string `json:"id,omitempty"`
	Type_                   string `json:"$type,omitempty"`
}
