/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Lets you set a color for a card based on its project.
type ProjectBasedColorCoding struct {
	Id            string         `json:"id,omitempty"`
	Type_         string         `json:"$type,omitempty"`
	ProjectColors []ProjectColor `json:"projectColors,omitempty"`
}
