/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

type AttributeBasedSwimlaneSettings struct {
	Enabled bool                           `json:"enabled,omitempty"`
	Id      string                         `json:"id,omitempty"`
	Type_   string                         `json:"$type,omitempty"`
	Field   *FilterField                   `json:"field,omitempty"`
	Values  []SwimlaneEntityAttributeValue `json:"values,omitempty"`
}
