/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an enumeration value in YouTrack.
type EnumBundleElement struct {
	LocalizedName string `json:"localizedName,omitempty"`
}
