/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents users that have voted for the issue or its duplicates.
type IssueVoters struct {
	HasVote   bool            `json:"hasVote,omitempty"`
	Original  []User          `json:"original,omitempty"`
	Duplicate []DuplicateVote `json:"duplicate,omitempty"`
	Id        string          `json:"id,omitempty"`
	Type_     string          `json:"$type,omitempty"`
}
