/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an existing issue comment.
type IssueComment struct {
	Text         string            `json:"text,omitempty"`
	UsesMarkdown bool              `json:"usesMarkdown,omitempty"`
	TextPreview  string            `json:"textPreview,omitempty"`
	Created      int64             `json:"created,omitempty"`
	Updated      int64             `json:"updated,omitempty"`
	Author       *User             `json:"author,omitempty"`
	Issue        *Issue            `json:"issue,omitempty"`
	Attachments  []IssueAttachment `json:"attachments,omitempty"`
	Visibility   *Visibility       `json:"visibility,omitempty"`
	Deleted      bool              `json:"deleted,omitempty"`
	Id           string            `json:"id,omitempty"`
	Type_        string            `json:"$type,omitempty"`
}
