/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a custom field in YouTrack.
type CustomField struct {
	Name                   string               `json:"name,omitempty"`
	LocalizedName          string               `json:"localizedName,omitempty"`
	FieldType              *FieldType           `json:"fieldType,omitempty"`
	IsAutoAttached         bool                 `json:"isAutoAttached,omitempty"`
	IsDisplayedInIssueList bool                 `json:"isDisplayedInIssueList,omitempty"`
	Ordinal                int32                `json:"ordinal,omitempty"`
	Aliases                string               `json:"aliases,omitempty"`
	FieldDefaults          *CustomFieldDefaults `json:"fieldDefaults,omitempty"`
	HasRunningJob          bool                 `json:"hasRunningJob,omitempty"`
	IsUpdateable           bool                 `json:"isUpdateable,omitempty"`
	Instances              []ProjectCustomField `json:"instances,omitempty"`
	Id                     string               `json:"id,omitempty"`
	Type_                  string               `json:"$type,omitempty"`
}
