/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Telemetry data of the YouTrack installation.
type Telemetry struct {
	InstallationFolder                 string       `json:"installationFolder,omitempty"`
	DatabaseLocation                   string       `json:"databaseLocation,omitempty"`
	LogsLocation                       string       `json:"logsLocation,omitempty"`
	AvailableProcessors                int32        `json:"availableProcessors,omitempty"`
	AvailableMemory                    string       `json:"availableMemory,omitempty"`
	AllocatedMemory                    string       `json:"allocatedMemory,omitempty"`
	UsedMemory                         string       `json:"usedMemory,omitempty"`
	Uptime                             string       `json:"uptime,omitempty"`
	StartedTime                        int64        `json:"startedTime,omitempty"`
	DatabaseBackgroundThreads          int32        `json:"databaseBackgroundThreads,omitempty"`
	PendingAsyncJobs                   int32        `json:"pendingAsyncJobs,omitempty"`
	CachedResultsCountInDBQueriesCache int32        `json:"cachedResultsCountInDBQueriesCache,omitempty"`
	DatabaseQueriesCacheHitRate        string       `json:"databaseQueriesCacheHitRate,omitempty"`
	BlobStringsCacheHitRate            string       `json:"blobStringsCacheHitRate,omitempty"`
	TotalTransactions                  int64        `json:"totalTransactions,omitempty"`
	TransactionsPerSecond              string       `json:"transactionsPerSecond,omitempty"`
	RequestsPerSecond                  string       `json:"requestsPerSecond,omitempty"`
	DatabaseSize                       string       `json:"databaseSize,omitempty"`
	FullDatabaseSize                   string       `json:"fullDatabaseSize,omitempty"`
	TextIndexSize                      string       `json:"textIndexSize,omitempty"`
	OnlineUsers                        *OnlineUsers `json:"onlineUsers,omitempty"`
	ReportCalculatorThreads            int32        `json:"reportCalculatorThreads,omitempty"`
	NotificationAnalyzerThreads        int32        `json:"notificationAnalyzerThreads,omitempty"`
	Id                                 string       `json:"id,omitempty"`
	Type_                              string       `json:"$type,omitempty"`
}
