/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a user who subscribed for notifications about an issue.
type IssueWatcher struct {
	User      *User  `json:"user,omitempty"`
	Issue     *Issue `json:"issue,omitempty"`
	IsStarred bool   `json:"isStarred,omitempty"`
	Id        string `json:"id,omitempty"`
	Type_     string `json:"$type,omitempty"`
}
