/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the command that was parsed from the provided query.
type ParsedCommand struct {
	Description string `json:"description,omitempty"`
	Error_      bool   `json:"error,omitempty"`
	Delete      bool   `json:"delete,omitempty"`
	Id          string `json:"id,omitempty"`
	Type_       string `json:"$type,omitempty"`
}
