/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Describes rules that define which colors are used for cards on the agile board.
type ColorCoding struct {
	Id    string `json:"id,omitempty"`
	Type_ string `json:"$type,omitempty"`
}
