/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an action when an entity is created or deleted in an issue. For example, a new comment is created in the issue.
type CreatedDeletedActivityItem struct {
	Id    string `json:"id,omitempty"`
	Type_ string `json:"$type,omitempty"`
}
