/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the change in the project attribute on an Issue.
type ProjectActivityItem struct {
	Target  *Issue       `json:"target,omitempty"`
	Removed *interface{} `json:"removed,omitempty"`
	Added   *interface{} `json:"added,omitempty"`
}
