/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Stores number of online user.
type OnlineUsers struct {
	Users int32  `json:"users,omitempty"`
	Id    string `json:"id,omitempty"`
	Type_ string `json:"$type,omitempty"`
}
