/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in the comments of an issue.
type CommentActivityItem struct {
	Target      *IssueComment  `json:"target,omitempty"`
	Removed     []IssueComment `json:"removed,omitempty"`
	Added       []IssueComment `json:"added,omitempty"`
	AuthorGroup *UserGroup     `json:"authorGroup,omitempty"`
}
