/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a single swimlane in case of AttributeBasedSwimlaneSettings.
type SwimlaneEntityAttributeValue struct {
	Id         string `json:"id,omitempty"`
	Type_      string `json:"$type,omitempty"`
	Name       string `json:"name,omitempty"`
	IsResolved bool   `json:"isResolved,omitempty"`
}
