/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in the list of attachments of an issue.
type AttachmentActivityItem struct {
	Target  *IssueAttachment  `json:"target,omitempty"`
	Removed []IssueAttachment `json:"removed,omitempty"`
	Added   []IssueAttachment `json:"added,omitempty"`
}
