/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in the `duration` attribute of a work item.
type WorkItemDurationActivityItem struct {
	Target  *IssueWorkItem `json:"target,omitempty"`
	Removed *DurationValue `json:"removed,omitempty"`
	Added   *DurationValue `json:"added,omitempty"`
}
