/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Shows if the board has any configuration problems.
type AgileStatus struct {
	Valid    bool   `json:"valid,omitempty"`
	HasJobs  bool   `json:"hasJobs,omitempty"`
	Errors   string `json:"errors,omitempty"`
	Warnings string `json:"warnings,omitempty"`
	Id       string `json:"id,omitempty"`
	Type_    string `json:"$type,omitempty"`
}
