/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Visibility settings of the comment that is added along with the command.
type CommandVisibility struct {
	Id    string `json:"id,omitempty"`
	Type_ string `json:"$type,omitempty"`
}
