/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the System settings that affect core functionality of YouTrack.
type SystemSettings struct {
	BaseUrl                   string `json:"baseUrl,omitempty"`
	MaxUploadFileSize         int64  `json:"maxUploadFileSize,omitempty"`
	MaxExportItems            int32  `json:"maxExportItems,omitempty"`
	AdministratorEmail        string `json:"administratorEmail,omitempty"`
	AllowStatisticsCollection bool   `json:"allowStatisticsCollection,omitempty"`
	IsApplicationReadOnly     bool   `json:"isApplicationReadOnly,omitempty"`
	Id                        string `json:"id,omitempty"`
	Type_                     string `json:"$type,omitempty"`
}
