/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Default settings for the version-type field.
type VersionBundleCustomFieldDefaults struct {
	Bundle        *VersionBundle         `json:"bundle,omitempty"`
	DefaultValues []VersionBundleElement `json:"defaultValues,omitempty"`
}
