/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents custom field settings for the particular project.
type ProjectCustomField struct {
	Field          *CustomField `json:"field,omitempty"`
	Project        *Project     `json:"project,omitempty"`
	CanBeEmpty     bool         `json:"canBeEmpty,omitempty"`
	EmptyFieldText string       `json:"emptyFieldText,omitempty"`
	Ordinal        int32        `json:"ordinal,omitempty"`
	IsPublic       bool         `json:"isPublic,omitempty"`
	HasRunningJob  bool         `json:"hasRunningJob,omitempty"`
	Id             string       `json:"id,omitempty"`
	Type_          string       `json:"$type,omitempty"`
}
