/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an activity that affects a custom field of an issue.
type CustomFieldActivityItem struct {
	Id      string       `json:"id,omitempty"`
	Type_   string       `json:"$type,omitempty"`
	Target  *Issue       `json:"target,omitempty"`
	Removed *interface{} `json:"removed,omitempty"`
	Added   *interface{} `json:"added,omitempty"`
}
