/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an update in the list of VCSChanges of an issue.
type VcsChangeActivityItem struct {
	Removed *interface{} `json:"removed,omitempty"`
	Added   *interface{} `json:"added,omitempty"`
	Author  *User        `json:"author,omitempty"`
}
