/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a sprint that is associated with an agile board. Each sprint can include issues from one or more projects.
type Sprint struct {
	Agile                 *Agile  `json:"agile,omitempty"`
	Name                  string  `json:"name,omitempty"`
	Goal                  string  `json:"goal,omitempty"`
	Start                 int64   `json:"start,omitempty"`
	Finish                int64   `json:"finish,omitempty"`
	Archived              bool    `json:"archived,omitempty"`
	IsDefault             bool    `json:"isDefault,omitempty"`
	Issues                []Issue `json:"issues,omitempty"`
	UnresolvedIssuesCount int32   `json:"unresolvedIssuesCount,omitempty"`
	PreviousSprint        *Sprint `json:"previousSprint,omitempty"`
	Id                    string  `json:"id,omitempty"`
	Type_                 string  `json:"$type,omitempty"`
}
