/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents email settings for this YouTrack installation.
type EmailSettings struct {
	IsEnabled    bool          `json:"isEnabled,omitempty"`
	Host         string        `json:"host,omitempty"`
	Port         int32         `json:"port,omitempty"`
	MailProtocol string        `json:"mailProtocol,omitempty"`
	Anonymous    bool          `json:"anonymous,omitempty"`
	Login        string        `json:"login,omitempty"`
	SslKey       *StorageEntry `json:"sslKey,omitempty"`
	From         string        `json:"from,omitempty"`
	ReplyTo      string        `json:"replyTo,omitempty"`
	Id           string        `json:"id,omitempty"`
	Type_        string        `json:"$type,omitempty"`
}
