/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the event when a user adds or removes a group to/from the Visibility settings of the target entity.
type VisibilityGroupActivityItem struct {
	TargetMember    string      `json:"targetMember,omitempty"`
	TargetSubMember string      `json:"targetSubMember,omitempty"`
	Removed         []UserGroup `json:"removed,omitempty"`
	Added           []UserGroup `json:"added,omitempty"`
}
