/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in the `attachments` attribute of an IssueComment.
type CommentAttachmentsActivityItem struct {
	Target  *IssueComment     `json:"target,omitempty"`
	Removed []IssueAttachment `json:"removed,omitempty"`
	Added   []IssueAttachment `json:"added,omitempty"`
}
