/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the user profile in YouTrack.
type GeneralUserProfile struct {
	DateFieldFormat *DateFormatDescriptor `json:"dateFieldFormat,omitempty"`
	Timezone        *TimeZoneDescriptor   `json:"timezone,omitempty"`
	Locale          *LocaleDescriptor     `json:"locale,omitempty"`
	Id              string                `json:"id,omitempty"`
	Type_           string                `json:"$type,omitempty"`
}
