/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the state of an issue in YouTrack.
type StateBundleElement struct {
	LocalizedName string `json:"localizedName,omitempty"`
	IsResolved    bool   `json:"isResolved,omitempty"`
}
