/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the notification settings in the profile of the specific user.
type NotificationsUserProfile struct {
	NotifyOnOwnChanges                     bool   `json:"notifyOnOwnChanges,omitempty"`
	JabberNotificationsEnabled             bool   `json:"jabberNotificationsEnabled,omitempty"`
	EmailNotificationsEnabled              bool   `json:"emailNotificationsEnabled,omitempty"`
	MentionNotificationsEnabled            bool   `json:"mentionNotificationsEnabled,omitempty"`
	DuplicateClusterNotificationsEnabled   bool   `json:"duplicateClusterNotificationsEnabled,omitempty"`
	MailboxIntegrationNotificationsEnabled bool   `json:"mailboxIntegrationNotificationsEnabled,omitempty"`
	UsePlainTextEmails                     bool   `json:"usePlainTextEmails,omitempty"`
	AutoWatchOnComment                     bool   `json:"autoWatchOnComment,omitempty"`
	AutoWatchOnCreate                      bool   `json:"autoWatchOnCreate,omitempty"`
	AutoWatchOnVote                        bool   `json:"autoWatchOnVote,omitempty"`
	AutoWatchOnUpdate                      bool   `json:"autoWatchOnUpdate,omitempty"`
	Id                                     string `json:"id,omitempty"`
	Type_                                  string `json:"$type,omitempty"`
}
