/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Comment is visible for all the users who can read the issue.
type CommandUnlimitedVisibility struct {
	Id    string `json:"id,omitempty"`
	Type_ string `json:"$type,omitempty"`
}
