/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents project settings for the owned field.
type OwnedProjectCustomField struct {
	Bundle        *OwnedBundle         `json:"bundle,omitempty"`
	DefaultValues []OwnedBundleElement `json:"defaultValues,omitempty"`
}
