/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents issue links of a particular link type (for example, 'relates to').
type IssueLink struct {
	Direction     string         `json:"direction,omitempty"`
	LinkType      *IssueLinkType `json:"linkType,omitempty"`
	Issues        []Issue        `json:"issues,omitempty"`
	TrimmedIssues []Issue        `json:"trimmedIssues,omitempty"`
	Id            string         `json:"id,omitempty"`
	Type_         string         `json:"$type,omitempty"`
}
