/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an event when a user creates a new issue.
type IssueCreatedActivityItem struct {
	Target  *Issue  `json:"target,omitempty"`
	Removed []Issue `json:"removed,omitempty"`
	Added   []Issue `json:"added,omitempty"`
}
