/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents settings for a single board column
type AgileColumn struct {
	Presentation string                  `json:"presentation,omitempty"`
	IsResolved   bool                    `json:"isResolved,omitempty"`
	Ordinal      int32                   `json:"ordinal,omitempty"`
	Parent       *ColumnSettings         `json:"parent,omitempty"`
	WipLimit     *WipLimit               `json:"wipLimit,omitempty"`
	FieldValues  []AgileColumnFieldValue `json:"fieldValues,omitempty"`
	Id           string                  `json:"id,omitempty"`
	Type_        string                  `json:"$type,omitempty"`
}
