/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents users that are subscribed to notifications about the issue.
type IssueWatchers struct {
	HasStar           bool           `json:"hasStar,omitempty"`
	IssueWatchers     []IssueWatcher `json:"issueWatchers,omitempty"`
	DuplicateWatchers []IssueWatcher `json:"duplicateWatchers,omitempty"`
	Id                string         `json:"id,omitempty"`
	Type_             string         `json:"$type,omitempty"`
}
