/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in the issue when it was added to or removed from an agile board sprint.
type SprintActivityItem struct {
	Target  *Issue   `json:"target,omitempty"`
	Removed []Sprint `json:"removed,omitempty"`
	Added   []Sprint `json:"added,omitempty"`
}
