/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a work item in an issue.
type IssueWorkItem struct {
	Author       *User          `json:"author,omitempty"`
	Creator      *User          `json:"creator,omitempty"`
	Text         string         `json:"text,omitempty"`
	TextPreview  string         `json:"textPreview,omitempty"`
	WorkType     *WorkItemType  `json:"type,omitempty"`
	Created      int64          `json:"created,omitempty"`
	Updated      int64          `json:"updated,omitempty"`
	Duration     *DurationValue `json:"duration,omitempty"`
	Date         int64          `json:"date,omitempty"`
	Issue        *Issue         `json:"issue,omitempty"`
	UsesMarkdown bool           `json:"usesMarkdown,omitempty"`
	Id           string         `json:"id,omitempty"`
	Type         string         `json:"$type,omitempty"`
}
