/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in the `type` attribute of the work item.
type WorkItemTypeActivityItem struct {
	Target  *IssueWorkItem `json:"target,omitempty"`
	Removed []WorkItemType `json:"removed,omitempty"`
	Added   []WorkItemType `json:"added,omitempty"`
}
