/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an issue in YouTrack.
type Issue struct {
	IdReadable          string            `json:"idReadable,omitempty"`
	Created             int64             `json:"created,omitempty"`
	Updated             int64             `json:"updated,omitempty"`
	Resolved            int64             `json:"resolved,omitempty"`
	NumberInProject     int64             `json:"numberInProject,omitempty"`
	Project             *Project          `json:"project,omitempty"`
	Summary             string            `json:"summary,omitempty"`
	Description         string            `json:"description,omitempty"`
	UsesMarkdown        bool              `json:"usesMarkdown,omitempty"`
	WikifiedDescription string            `json:"wikifiedDescription,omitempty"`
	Reporter            *User             `json:"reporter,omitempty"`
	Updater             *User             `json:"updater,omitempty"`
	DraftOwner          *User             `json:"draftOwner,omitempty"`
	IsDraft             bool              `json:"isDraft,omitempty"`
	Visibility          *Visibility       `json:"visibility,omitempty"`
	Votes               int32             `json:"votes,omitempty"`
	Comments            []IssueComment    `json:"comments,omitempty"`
	CommentsCount       int32             `json:"commentsCount,omitempty"`
	Tags                []IssueTag        `json:"tags,omitempty"`
	Links               []IssueLink       `json:"links,omitempty"`
	ExternalIssue       *ExternalIssue    `json:"externalIssue,omitempty"`
	CustomFields        interface{}       `json:"customFields,omitempty"`
	Voters              *IssueVoters      `json:"voters,omitempty"`
	Watchers            *IssueWatchers    `json:"watchers,omitempty"`
	Attachments         []IssueAttachment `json:"attachments,omitempty"`
	Subtasks            *IssueLink        `json:"subtasks,omitempty"`
	Parent              *IssueLink        `json:"parent,omitempty"`
	Id                  string            `json:"id,omitempty"`
	Type_               string            `json:"$type,omitempty"`
}
