/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Default settings for the enum-type field.
type EnumBundleCustomFieldDefaults struct {
	Bundle        *EnumBundle         `json:"bundle,omitempty"`
	DefaultValues []EnumBundleElement `json:"defaultValues,omitempty"`
}
