/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents time tracking settings in the user's profile.
type TimeTrackingUserProfile struct {
	PeriodFormat *PeriodFieldFormat `json:"periodFormat,omitempty"`
	Id           string             `json:"id,omitempty"`
	Type_        string             `json:"$type,omitempty"`
}
