/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

type UserProfiles struct {
	General       *GeneralUserProfile       `json:"general,omitempty"`
	Notifications *NotificationsUserProfile `json:"notifications,omitempty"`
	Timetracking  *TimeTrackingUserProfile  `json:"timetracking,omitempty"`
	Id            string                    `json:"id,omitempty"`
	Type_         string                    `json:"$type,omitempty"`
}
