/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an issue tag.
type IssueTag struct {
	Owner          *User       `json:"owner,omitempty"`
	VisibleFor     *UserGroup  `json:"visibleFor,omitempty"`
	UpdateableBy   *UserGroup  `json:"updateableBy,omitempty"`
	Issues         []Issue     `json:"issues,omitempty"`
	Color          *FieldStyle `json:"color,omitempty"`
	UntagOnResolve bool        `json:"untagOnResolve,omitempty"`
}
