/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents color setting for one project on the board.
type ProjectColor struct {
	Project *Project    `json:"project,omitempty"`
	Color   *FieldStyle `json:"color,omitempty"`
	Id      string      `json:"id,omitempty"`
	Type_   string      `json:"$type,omitempty"`
}
