/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the Resource Sharing (CORS) configuration of the service.
type RestCorsSettings struct {
	AllowedOrigins  string `json:"allowedOrigins,omitempty"`
	AllowAllOrigins bool   `json:"allowAllOrigins,omitempty"`
	Id              string `json:"id,omitempty"`
	Type_           string `json:"$type,omitempty"`
}
