/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the System Language settings.
type LocaleSettings struct {
	Locale *LocaleDescriptor `json:"locale,omitempty"`
	IsRTL  bool              `json:"isRTL,omitempty"`
	Id     string            `json:"id,omitempty"`
	Type_  string            `json:"$type,omitempty"`
}
