/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the period field in the issue.
type PeriodIssueCustomField struct {
	Id    string       `json:"id,omitempty"`
	Type_ string       `json:"$type,omitempty"`
	Value *PeriodValue `json:"value,omitempty"`
}
