/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents default settings for the user-type field.
type UserCustomFieldDefaults struct {
	CanBeEmpty     bool         `json:"canBeEmpty,omitempty"`
	EmptyFieldText string       `json:"emptyFieldText,omitempty"`
	IsPublic       bool         `json:"isPublic,omitempty"`
	Parent         *CustomField `json:"parent,omitempty"`
	Id             string       `json:"id,omitempty"`
	Type_          string       `json:"$type,omitempty"`
	Bundle         *UserBundle  `json:"bundle,omitempty"`
	DefaultValues  []User       `json:"defaultValues,omitempty"`
}
