/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a page object that wraps a list of issue activities. The main advantage of the page in comparision to a list of activities is cursors. The page provides boundary marks that allow continuous iteration over the activities from the place the page is finished.
type ActivityCursorPage struct {
	Reverse      bool           `json:"reverse,omitempty"`
	BeforeCursor string         `json:"beforeCursor,omitempty"`
	AfterCursor  string         `json:"afterCursor,omitempty"`
	HasBefore    bool           `json:"hasBefore,omitempty"`
	HasAfter     bool           `json:"hasAfter,omitempty"`
	Activities   []ActivityItem `json:"activities,omitempty"`
	Id           string         `json:"id,omitempty"`
	Type_        string         `json:"$type,omitempty"`
}
