/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Describes sprints configuration.
type SprintsSettings struct {
	IsExplicit           bool         `json:"isExplicit,omitempty"`
	CardOnSeveralSprints bool         `json:"cardOnSeveralSprints,omitempty"`
	DefaultSprint        *Sprint      `json:"defaultSprint,omitempty"`
	DisableSprints       bool         `json:"disableSprints,omitempty"`
	ExplicitQuery        string       `json:"explicitQuery,omitempty"`
	SprintSyncField      *CustomField `json:"sprintSyncField,omitempty"`
	HideSubtasksOfCards  bool         `json:"hideSubtasksOfCards,omitempty"`
	Id                   string       `json:"id,omitempty"`
	Type_                string       `json:"$type,omitempty"`
}
