/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Swimlane settings for the case, when each swimlane is represented by an issue and contains this issue's subtasks.
type IssueBasedSwimlaneSettings struct {
	Enabled         bool            `json:"enabled,omitempty"`
	Id              string          `json:"id,omitempty"`
	Type_           string          `json:"$type,omitempty"`
	Field           *FilterField    `json:"field,omitempty"`
	DefaultCardType *SwimlaneValue  `json:"defaultCardType,omitempty"`
	Values          []SwimlaneValue `json:"values,omitempty"`
}
