/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the all custom fields that may have multiple values in the issue.
type DatabaseMultiValueIssueCustomField struct {
	Id                 string              `json:"id,omitempty"`
	Type_              string              `json:"$type,omitempty"`
	ProjectCustomField *ProjectCustomField `json:"projectCustomField,omitempty"`
	Value              interface{}         `json:"value,omitempty"`
}
