/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a set of builds in YouTrack.
type BuildBundle struct {
	Values []BuildBundleElement `json:"values,omitempty"`
}
