/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in a `String`-type attribute with the support of markup: `description` in an Issue or IssueWorkItem, and the `text` of the IssueComment. This entity lets you get the rendered text after the change.
type TextMarkupActivityItem struct {
	Removed string `json:"removed,omitempty"`
	Added   string `json:"added,omitempty"`
	Markup  string `json:"markup,omitempty"`
}
