/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a file that is attached to an issue or a comment.
type IssueAttachment struct {
	Name          string        `json:"name,omitempty"`
	Author        *User         `json:"author,omitempty"`
	Created       int64         `json:"created,omitempty"`
	Updated       int64         `json:"updated,omitempty"`
	Size          int64         `json:"size,omitempty"`
	Extension     string        `json:"extension,omitempty"`
	Charset       string        `json:"charset,omitempty"`
	MimeType      string        `json:"mimeType,omitempty"`
	MetaData      string        `json:"metaData,omitempty"`
	Draft         bool          `json:"draft,omitempty"`
	Removed       bool          `json:"removed,omitempty"`
	Base64Content string        `json:"base64Content,omitempty"`
	Url           string        `json:"url,omitempty"`
	Visibility    *Visibility   `json:"visibility,omitempty"`
	Issue         *Issue        `json:"issue,omitempty"`
	Comment       *IssueComment `json:"comment,omitempty"`
	ThumbnailURL  string        `json:"thumbnailURL,omitempty"`
	Id            string        `json:"id,omitempty"`
	Type_         string        `json:"$type,omitempty"`
}
