/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a set of values of the enumeration type in YouTrack.
type EnumBundle struct {
	Values []EnumBundleElement `json:"values,omitempty"`
}
