/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an agile board configuration.
type Agile struct {
	Name                     string            `json:"name,omitempty"`
	Owner                    *User             `json:"owner,omitempty"`
	VisibleFor               *UserGroup        `json:"visibleFor,omitempty"`
	VisibleForProjectBased   bool              `json:"visibleForProjectBased,omitempty"`
	UpdateableBy             *UserGroup        `json:"updateableBy,omitempty"`
	UpdateableByProjectBased bool              `json:"updateableByProjectBased,omitempty"`
	OrphansAtTheTop          bool              `json:"orphansAtTheTop,omitempty"`
	HideOrphansSwimlane      bool              `json:"hideOrphansSwimlane,omitempty"`
	EstimationField          *CustomField      `json:"estimationField,omitempty"`
	OriginalEstimationField  *CustomField      `json:"originalEstimationField,omitempty"`
	Projects                 []Project         `json:"projects,omitempty"`
	Sprints                  []Sprint          `json:"sprints,omitempty"`
	CurrentSprint            *Sprint           `json:"currentSprint,omitempty"`
	ColumnSettings           *ColumnSettings   `json:"columnSettings,omitempty"`
	SwimlaneSettings         *SwimlaneSettings `json:"swimlaneSettings,omitempty"`
	SprintsSettings          *SprintsSettings  `json:"sprintsSettings,omitempty"`
	ColorCoding              *ColorCoding      `json:"colorCoding,omitempty"`
	Status                   *AgileStatus      `json:"status,omitempty"`
	Id                       string            `json:"id,omitempty"`
	Type_                    string            `json:"$type,omitempty"`
}
