/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents time tracking settings of the project.
type ProjectTimeTrackingSettings struct {
	Enabled       bool                `json:"enabled,omitempty"`
	Estimate      *ProjectCustomField `json:"estimate,omitempty"`
	TimeSpent     *ProjectCustomField `json:"timeSpent,omitempty"`
	WorkItemTypes []WorkItemType      `json:"workItemTypes,omitempty"`
	Project       *Project            `json:"project,omitempty"`
	Id            string              `json:"id,omitempty"`
	Type_         string              `json:"$type,omitempty"`
}
