/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Work schedule settings.
type WorkTimeSettings struct {
	MinutesADay    int32  `json:"minutesADay,omitempty"`
	WorkDays       int32  `json:"workDays,omitempty"`
	FirstDayOfWeek int32  `json:"firstDayOfWeek,omitempty"`
	DaysAWeek      int32  `json:"daysAWeek,omitempty"`
	Id             string `json:"id,omitempty"`
	Type_          string `json:"$type,omitempty"`
}
