/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an issue property, which can be a predefined field, a custom field, a link, and so on.
type FilterField struct {
	Name  string `json:"name,omitempty"`
	Id    string `json:"id,omitempty"`
	Type_ string `json:"$type,omitempty"`
}
