/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a change in a list of work items in an issue.
type WorkItemActivityItem struct {
	Target  *IssueWorkItem  `json:"target,omitempty"`
	Removed []IssueWorkItem `json:"removed,omitempty"`
	Added   []IssueWorkItem `json:"added,omitempty"`
}
