/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Sets a card color based on a value of some custom field.
type FieldBasedColorCoding struct {
	Id        string       `json:"id,omitempty"`
	Type_     string       `json:"$type,omitempty"`
	Prototype *CustomField `json:"prototype,omitempty"`
}
