/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents default project-related settings of the custom field. These settings are applied at the moment when the custom field is attached to a project. After that, any changes in default settings do not affect the field settings for this project.
type CustomFieldDefaults struct {
	CanBeEmpty     bool         `json:"canBeEmpty,omitempty"`
	EmptyFieldText string       `json:"emptyFieldText,omitempty"`
	IsPublic       bool         `json:"isPublic,omitempty"`
	Parent         *CustomField `json:"parent,omitempty"`
	Id             string       `json:"id,omitempty"`
	Type_          string       `json:"$type,omitempty"`
}
