/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents an event when a user resolves an issue.
type IssueResolvedActivityItem struct {
	Removed int64 `json:"removed,omitempty"`
	Added   int64 `json:"added,omitempty"`
}
