/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents a group of users.
type UserGroup struct {
	Name           string   `json:"name,omitempty"`
	RingId         string   `json:"ringId,omitempty"`
	UsersCount     int64    `json:"usersCount,omitempty"`
	Icon           string   `json:"icon,omitempty"`
	AllUsersGroup  bool     `json:"allUsersGroup,omitempty"`
	TeamForProject *Project `json:"teamForProject,omitempty"`
	Id             string   `json:"id,omitempty"`
	Type_          string   `json:"$type,omitempty"`
}
