/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * API version: 2021.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utrack

// Represents the Notifications settings of the YouTrack service.
type NotificationSettings struct {
	EmailSettings  *EmailSettings  `json:"emailSettings,omitempty"`
	JabberSettings *JabberSettings `json:"jabberSettings,omitempty"`
	Id             string          `json:"id,omitempty"`
	Type_          string          `json:"$type,omitempty"`
}
